// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRwQmTF1-riLZdRZFfx26VJbWAEeWZN0Q',
    appId: '1:141828214100:web:e9fa64eed46b6b6d04ccc1',
    messagingSenderId: '141828214100',
    projectId: 'journey-joy-dbc69',
    authDomain: 'journey-joy-dbc69.firebaseapp.com',
    storageBucket: 'journey-joy-dbc69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2tc0jwWCc9DMwyt3oLsZ05Y8JOzjd8a8',
    appId: '1:141828214100:android:4d7e781ab8eeeaf004ccc1',
    messagingSenderId: '141828214100',
    projectId: 'journey-joy-dbc69',
    storageBucket: 'journey-joy-dbc69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-gEzvNGgj3QliFO2Iffgw8gHtmaDdeFI',
    appId: '1:141828214100:ios:da7fb6f87d89680804ccc1',
    messagingSenderId: '141828214100',
    projectId: 'journey-joy-dbc69',
    storageBucket: 'journey-joy-dbc69.firebasestorage.app',
    iosBundleId: 'com.journeyjoy.journeyJoy',
  );
}
